server:
  port: 8080
  forward-headers-strategy: framework
  use-forward-headers: true

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  services:
    url: http://localhost:8080/info624
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,shutdown
  endpoint:
    health:
      enabled: true
      show-details: never
      show-components: never
      probes:
        enabled: true